[project]
name = "zephyr"
version = "0.1.0"
description = "High-Performance Pure ONNX Embedding Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]==0.124.4",
    "tokenizers==0.22.1",
    "huggingface-hub==1.2.3",
    "numpy==2.3.5",
    "omegaconf==2.3.0",
    "onnx==1.20.0",
    "httpx==0.28.1",
]

[project.optional-dependencies]
cuda = ["onnxruntime-gpu[cuda,cudnn]==1.23.2"]
migraphx = [
    "onnxruntime-migraphx>=1.23.0",
]
cpu = [
    "onnxruntime>=1.23.2",
]

[[tool.uv.index]]
name = "migraphx"
url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-7.1.1/"
explicit = false

[dependency-groups]
dev = [
    "pytest==8.3.4",
    "httpx==0.28.1",
]
